---
- name: Create pandeeswari user
  hosts: webservers
  become: true

  tasks:
    - name: Create pandeeswari user
      user:
        name: pandeeswari
        shell: /bin/bash
        createhome: yes
