---
- hosts: webserver
  ignore_errors: true
  ignore_unreachable: true
  remote_user: ubuntu
  become: true
  become_user: pandeeswari
  tasks:
    - name: downloading tomcat
      get_url:
        url: https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.6/bin/apache-tomcat-10.1.6.tar.gz
        dest: /opt
    - name: extracting tomcat
      unarchive:
        src: /opt/apache-tomcat-10.1.6.tar.gz
        dest: /opt
        remote_src: yes
    - name: installing java
      apt:
        name: default-jdk
        state: present
    - name: sample war downloading
      get_url:
        url: https://tomcat.apache.org/tomcat-7.0-doc/appdev/sample/sample.war
        dest: /opt/apache-tomcat-10.1.6/webapps
      notify:
        - restart tomcat
  handlers:
    - name: restart tomcat
      service:
        name: tomcat
        state: restarted
      ignore_errors: true
